spring:
  application:
    name: solicitudes

  datasource:
    url: jdbc:h2:mem:solicitudesdb
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    open-in-view: false

  h2:
    console:
      enabled: true
      path: /h2-console